name = "tmxparser"

version = "2.1.0.pvx1"

authors = [
    "Tamir Atlas, Andrew Kelley et al."
]

description = \
    """
    C++ library for parsing the maps generated by the Map Editor called Tiled.
    """

build_requires = [
]

@early()
def variants():
    from rez.package_py_utils import expand_requires
    requires = ["platform-**", "arch-**", "os-**"]
    return [expand_requires(*requires)]

config = {
    "local_packages_path": "${PVX_REZ_LOCAL_THIRDPARTY_DIR}",
    "release_packages_path": "${PVX_REZ_RELEASE_THIRDPARTY_DIR}",
}

uuid = "repository.tmxparser"

def commands():
    env.LD_LIBRARY_PATH.append("{root}/lib")

    env.TMXPARSER_INCLUDE_DIR = "{root}/include"
    env.TMXPARSER_LIB_DIR = "{root}/lib"
    env.TMXPARSER_LIBRARIES = "tmxparser"
